"""Freeze the corpus with SHA256 hashes before any model run.

Run this ONCE before running any ASR model over the corpus.
After running, commit MANIFEST_SHA256.txt to the repo.

Per ARCHITECTURE.md design rule #4:
  "No corpus clip is added or dropped after seeing model results.
   Freeze via SHA256 manifest before any model run."

Usage:
    python3 bench/corpus/freeze_manifest.py \\
        [--corpus bench/corpus/tier_a_recorded] \\
        [--output bench/corpus/tier_a_recorded/MANIFEST_SHA256.txt]

    # Verify an existing manifest (check nothing has changed):
    python3 bench/corpus/freeze_manifest.py --verify
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_CORPUS = _REPO_ROOT / "bench" / "corpus" / "tier_a_recorded"
_DEFAULT_MANIFEST = _DEFAULT_CORPUS / "MANIFEST_SHA256.txt"

_INCLUDE_EXTENSIONS = {
    ".wav", ".mp3", ".ogg", ".flac", ".m4a",  # audio
    ".json",                                    # ground truth + label files
}
_EXCLUDE_NAMES = {"MANIFEST_SHA256.txt"}


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def collect_files(corpus_dir: Path) -> list[Path]:
    """Return all corpus files that should be in the manifest, sorted."""
    return sorted(
        p for p in corpus_dir.rglob("*")
        if p.is_file()
        and p.suffix.lower() in _INCLUDE_EXTENSIONS
        and p.name not in _EXCLUDE_NAMES
    )


def write_manifest(corpus_dir: Path, manifest_path: Path) -> int:
    """Hash all corpus files and write the manifest. Returns file count."""
    files = collect_files(corpus_dir)

    if not files:
        print(f"⚠ No corpus files found in {corpus_dir}")
        print("  (Audio recordings go in bench/corpus/tier_a_recorded/audio/)")
        print("  Writing an empty manifest to record the freeze timestamp.")

    lines = [
        f"# SautiCivic Bridge — Corpus SHA256 Manifest",
        f"# Frozen: {datetime.now(timezone.utc).isoformat()}",
        f"# Corpus: {corpus_dir}",
        f"# Files:  {len(files)}",
        f"# DO NOT edit this file manually.",
        f"# Regenerate with: python3 bench/corpus/freeze_manifest.py",
        "",
    ]

    for f in files:
        rel = f.relative_to(corpus_dir)
        digest = sha256_file(f)
        lines.append(f"{digest}  {rel}")
        print(f"  {digest[:12]}...  {rel}")

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n✓ Manifest written: {manifest_path}  ({len(files)} files)")
    return len(files)


def verify_manifest(corpus_dir: Path, manifest_path: Path) -> bool:
    """Verify all files in the manifest still match their stored hashes."""
    if not manifest_path.exists():
        print(f"ERROR: Manifest not found: {manifest_path}")
        return False

    expected: dict[str, str] = {}
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        digest, rel_path = line.split(None, 1)
        expected[rel_path.strip()] = digest

    if not expected:
        print("⚠ Manifest exists but contains no file entries (corpus may be empty).")
        return True

    ok = True
    for rel_path, expected_digest in sorted(expected.items()):
        full = corpus_dir / rel_path
        if not full.exists():
            print(f"  MISSING  {rel_path}")
            ok = False
            continue
        actual = sha256_file(full)
        if actual != expected_digest:
            print(f"  CHANGED  {rel_path}")
            print(f"    expected: {expected_digest}")
            print(f"    actual:   {actual}")
            ok = False
        else:
            print(f"  OK       {rel_path}")

    if ok:
        print(f"\n✓ All {len(expected)} files verified — corpus is unchanged.")
    else:
        print(f"\n✗ Verification FAILED — corpus has changed since manifest was written.")
    return ok


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="SHA256 freeze/verify the corpus manifest.")
    p.add_argument("--corpus", type=Path, default=_DEFAULT_CORPUS)
    p.add_argument("--output", type=Path, default=_DEFAULT_MANIFEST)
    p.add_argument(
        "--verify",
        action="store_true",
        help="Verify existing manifest instead of writing a new one.",
    )
    return p.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    if args.verify:
        ok = verify_manifest(args.corpus, args.output)
        sys.exit(0 if ok else 1)
    else:
        write_manifest(args.corpus, args.output)
